apiVersion: v1
kind: ConfigMap
metadata:
  name: financial-tracker-config
  namespace: financial-tracker
data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: financial-trackerdb
  OLLAMA_URL: http://ollama-service:11434
  SERVER_FORWARD_HEADERS_STRATEGY: native
